@BASE_URL = http://localhost:5000


POST {{BASE_URL}}/api/send-email 
Content-Type: application/json

{
    "to": ["mechseiko@gmail.com", "saadidris23@gmail.com"],
    "text": "nothing to see here",
    "subject": "Test120",
    "templateId":"69979797c03a8af2383efb0a",
    "templateParams": {
        "name": "ihud"
    }
}

###

POST {{BASE_URL}}/api/template
Content-Type: application/json

{
    "title": "new Template",
    "description": "nothing to see here",
    "body": "<strong>hello,{{name}}</strong>",
    "subject": "Test120"
}


